# Generated by Django 5.1.5 on 2025-02-04 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('diplomation', '0001_initial'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect', models.TextField()),
                ('cooldown', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('class_type', models.CharField(choices=[('void_ranger', 'Void Ranger'), ('cyber_warrior', 'Cyber Warrior'), ('hacker', 'Hacker'), ('pilot', 'Pilot')], default='void_ranger', max_length=50)),
                ('hp', models.IntegerField(default=240)),
                ('max_hp', models.IntegerField(default=300)),
                ('energy', models.IntegerField(default=80)),
                ('max_energy', models.IntegerField(default=120)),
                ('stamina', models.IntegerField(default=120)),
                ('strength', models.IntegerField(default=18)),
                ('defense', models.IntegerField(default=12)),
                ('agility', models.IntegerField(default=14)),
                ('intelligence', models.IntegerField(default=10)),
                ('luck', models.IntegerField(default=6)),
                ('credits', models.DecimalField(decimal_places=2, default=250, max_digits=12)),
                ('experience', models.IntegerField(default=3500)),
                ('next_level_exp', models.IntegerField(default=5000)),
                ('fights_won', models.IntegerField(default=0)),
                ('fights_lost', models.IntegerField(default=0)),
                ('missions_completed', models.IntegerField(default=0)),
                ('missions_failed', models.IntegerField(default=0)),
                ('equipped_armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.armor')),
                ('equipped_weapon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.weapon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_reputations', to='diplomation.faction')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputations', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plasma', 'Plasma'), ('EMP', 'EMP'), ('radiation', 'Radiation')], max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistances', to='player.player')),
            ],
        ),
    ]
