# Generated by Django 5.1.5 on 2025-02-04 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('npc', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Ship', max_length=100)),
                ('ship_type', models.CharField(choices=[('fighter', 'Fighter'), ('freighter', 'Freighter'), ('explorer', 'Explorer'), ('battleship', 'Battleship')], max_length=50)),
                ('hp', models.IntegerField(default=1000)),
                ('max_hp', models.IntegerField(default=1000)),
                ('shield', models.IntegerField(default=500)),
                ('max_shield', models.IntegerField(default=500)),
                ('speed', models.IntegerField(default=50)),
                ('cargo_capacity', models.IntegerField(default=100)),
                ('fuel_capacity', models.IntegerField(default=200)),
                ('weapon_slots', models.IntegerField(default=2)),
                ('armor_slots', models.IntegerField(default=2)),
                ('crew_capacity', models.IntegerField(default=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='player.player')),
            ],
        ),
        migrations.CreateModel(
            name='ShipArmor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('defense_bonus', models.IntegerField(default=20)),
                ('special_effect', models.TextField(blank=True, null=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='ship.ship')),
            ],
        ),
        migrations.CreateModel(
            name='ShipCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('pilot', 'Pilot'), ('engineer', 'Engineer'), ('gunner', 'Gunner'), ('medic', 'Medic'), ('scientist', 'Scientist')], max_length=50)),
                ('skill_level', models.IntegerField(default=1)),
                ('npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_member', to='npc.npc')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='ship.ship')),
            ],
        ),
        migrations.CreateModel(
            name='ShipUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect', models.TextField()),
                ('energy_cost', models.IntegerField(default=10)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='ship.ship')),
            ],
        ),
        migrations.CreateModel(
            name='ShipWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('damage', models.IntegerField(default=50)),
                ('critical_chance', models.FloatField(default=10.0)),
                ('energy_consumption', models.IntegerField(default=5)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='ship.ship')),
            ],
        ),
    ]
