# Generated by Django 5.1.5 on 2025-02-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('species_type', models.CharField(choices=[('intelligent', 'Intelligent'), ('primitive', 'Primitive'), ('animal', 'Animal'), ('synthetic', 'Synthetic AI')], max_length=50)),
                ('lifespan', models.IntegerField(default=100)),
                ('average_height', models.FloatField(default=1.8)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesFaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_faction', models.CharField(choices=[('majority', 'Majority Population'), ('minority', 'Minority Population'), ('rulers', 'Ruling Class'), ('slaves', 'Enslaved Population')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('allies', models.ManyToManyField(blank=True, to='diplomation.faction')),
            ],
        ),
    ]
