# Generated by Django 5.1.5 on 2025-02-04 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diplomation', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='capital_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_of', to='space.starsystem'),
        ),
        migrations.AddField(
            model_name='faction',
            name='controlled_systems',
            field=models.ManyToManyField(blank=True, related_name='controlled_by', to='space.starsystem'),
        ),
        migrations.AddField(
            model_name='faction',
            name='enemies',
            field=models.ManyToManyField(blank=True, to='diplomation.faction'),
        ),
        migrations.AddField(
            model_name='species',
            name='homeworld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inhabitants', to='space.planet'),
        ),
        migrations.AddField(
            model_name='speciesfaction',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_members', to='diplomation.faction'),
        ),
        migrations.AddField(
            model_name='speciesfaction',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faction_affiliations', to='diplomation.species'),
        ),
    ]
